### PR TITLE
Set "CONNECT" & safe_ports restriction as optionnal

### PR DESCRIPTION
**Pull request by thomsh**
### Description
Some restrictions are not configurable by attributes in the squid.conf
- For Web Socket on tcp 80,  CONNECT is required but cannot be allowed by any way.
- Connection are limited to a default safe ports list, _if you don't need any restriction on tcp port you don't need that_.
This new behaviors are not enabled by default.

### Issues Resolved

None.

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by damacus** [comment]
@Xorima can you work your CircleCI magic on this when you get a chance please?

**Comment by damacus** [comment]
Hey @thomsh thanks for the PR! 

We ideally want a green build before we can merge into master. Right now this cookbook hasn't got the Sous-Chef's love since it was moved into our Organisation.

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/squid/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Xorima** [comment]
@thomsh Appologies for how long it took for me to circleci this cookbook, can you just check everything is in order when you get a moment?

**Comment by thomsh** [comment]
@Xorima LGTM, just append a line in the changelog, as your "danger" ci report it.
Actually I use this change in prod.

**Pull request merged**
