### PR TITLE
Fix #86. Remove unused network detection which break some setups

### LINKED ISSUE #86: Fails while fetching IP and netmask
### Cookbook version
4.0.2

### Chef-client version
chef-12.21.3-1.el6.x86_64

### Platform Details
CentOS release 6.9 (Final) 
CloudPlatform : Azure

### Scenario:
Recipe intermittently fails while fetching the netmask 
https://github.com/chef-cookbooks/squid/blob/master/recipes/default.rb#L23

### Steps to Reproduce:
We have included the default recipe in one of our cookbook ( basically which setup NAT ) and running chef-client from bootstrap script ( which executes when server comes up for the very first time).

### Expected Result:
Squid recipe will fail. 

### Actual Result:
Don't have it handy right now. Will update once re-create the server.

### PR DESCRIPTION
**Pull request by thomsh**
### Description

listen_interface detection fail if you have one interface up without
address, like the main interface in a setup with vlan.

### Issues Resolved

#86 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

(All test failed unrelated)

### CODE REVIEW

**Comment by manojbhatt** [comment]
@thomsh : Did you check why it is failing to merge ?

**Comment by thomsh** [comment]
@manojbhatt Can be merge without conflicts, some Travis build failed but they were already broken

**Comment by manojbhatt** [comment]
@thomsh : I don't have merged rights so probably someone with merge rights can help. 
Do you know you any other way to get it merged.

**Comment by thomsh** [comment]
@manojbhatt Nope, but on my fork it's merged in master : https://github.com/thomsh/squid

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/squid/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
@thomsh and @manojbhatt do either of you fancy helping out maintain Squid on a more regular basis?

**Pull request merged**
