### PR TITLE
Allow use of syslog logger

### PR DESCRIPTION
**Pull request by josqu4red**
### Description

Previous version has an access log directive with hardcoded filename:
`<%= log_dir %>/access.log`
Replace `log_dir` with `log_destination` which can be a file path or a
syslog facility

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by josqu4red** [comment]
Tests fail `setenforce` on SELinux platforms

**Comment by tas50** [comment]
I realize the name of the attribute would be wrong, but this is a breaking change that would have pretty far reaching impacts on existing users. Can we do this while keeping the existing attribute name?

**Comment by josqu4red** [comment]
@tas50 Fine by me, will switch back to `log_dir`

**Comment by josqu4red** [comment]
Any update ?

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/squid/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
HI @josqu4red can you add a changelog please?

**Comment by Xorima** [comment]
Hey, 

Thank you for the PR. We are closing due to inactivity. 
If you feel this feature should be merged in, please reopen and rebase as your contributions are always welcome.

Sous Chefs

**Pull request closed without merging**
